# Generated by Django 5.1.7 on 2025-03-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-is_superuser', '-is_staff', 'last_name', 'first_name', 'email'], 'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
    ]
