# Generated by Django 5.1.7 on 2025-03-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['is_superuser', 'is_staff', 'email', 'last_name', 'first_name'], 'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
    ]
