# Generated by Django 5.1.7 on 2025-03-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email', 'first_name', 'last_name', 'is_superuser', 'is_staff'], 'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
    ]
