# Generated by Django 5.1.7 on 2025-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_user_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published', 'author']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='There should be some post content here, but I was empty and left as the default :(', max_length=2056),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
